os: osx
language: go
osx_image: xcode8

before_install:
  - brew update
  - brew outdated golang || brew upgrade golang
  - brew install opam
  - opam init -y
  - go version

install:
  - eval `opam config env`
  - opam pin add -y qcow-format git://github.com/mirage/ocaml-qcow#master
  - opam install -y uri qcow-format
  - export GOPATH=$TRAVIS_BUILD_DIR
    go get -u github.com/jteeuwen/go-bindata/...
  - export BUILD_PATH=$TRAVIS_BUILD_DIR/src/github.com/nlf/dlite
  - mkdir -p $BUILD_PATH
  - shopt -s extglob dotglob
  - mv !(src) $BUILD_PATH
  - shopt -u extglob dotglob

script:
  - cd $BUILD_PATH
  - go generate
  - go build
  - ./dlite

notifications:
  email:
    on_success: never
    on_failure: always
