os: osx
language: go
osx_image: xcode8

before_install:
  - brew update
  - brew outdated golang || brew upgrade golang
  - brew install opam
  - opam init -y
  - go version

install:
  - eval `opam config env`
  - opam pin add -y qcow-format git://github.com/mirage/ocaml-qcow#master
  - opam install -y uri qcow-format
  - go get -u github.com/jteeuwen/go-bindata/...

script:
  - go generate
  - go build
  - ./dlite --version || true

notifications:
  email:
    on_success: never
    on_failure: always
